"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-08-16 18:49:50.523144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currencies_json', sa.String(), nullable=False),
    sa.Column('base_currency', sa.Enum('CLP', 'JPY', 'USD', name='currency'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_currency', sa.Enum('CLP', 'JPY', 'USD', name='currency'), nullable=False),
    sa.Column('target_currency', sa.Enum('CLP', 'JPY', 'USD', name='currency'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_date'), ['date'], unique=False)

    op.create_table('fixed_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('currency', sa.Enum('CLP', 'JPY', 'USD', name='currency'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('currency', sa.Enum('CLP', 'JPY', 'USD', name='currency'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_date'), ['date'], unique=False)

    op.create_table('monthly_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('currency', sa.Enum('CLP', 'JPY', 'USD', name='currency'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_expenses_date'), ['date'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('jpy_requested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('clp_charged', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('effective_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_date'), ['date'], unique=False)

    op.create_table('card_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount_clp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_expenses_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_expenses_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_expenses_date'))
        batch_op.drop_index(batch_op.f('ix_card_expenses_card_id'))

    op.drop_table('card_expenses')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_date'))

    op.drop_table('transfers')
    with op.batch_alter_table('monthly_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_expenses_date'))

    op.drop_table('monthly_expenses')
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_date'))

    op.drop_table('income')
    op.drop_table('fixed_expenses')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_date'))

    op.drop_table('exchange_rates')
    op.drop_table('credit_cards')
    op.drop_table('config')
    # ### end Alembic commands ###
