"""card_payments

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-16 19:19:10.412555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_payments_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_payments_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_payments_date'))
        batch_op.drop_index(batch_op.f('ix_card_payments_card_id'))

    op.drop_table('card_payments')
    # ### end Alembic commands ###
